import Head from "next/head";

import Header from "@/components/header";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    viewport: {
        width: "device-width",
        initialScale: 0,
    },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Header />
                {children}
            </body>
        </html>
    );
}
